# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: DownLoad Data 01 
          run: |
            wget -i filghturl.txt -P flight/
            git config --local user.name lzxue
            git config --local user.email lzx199065@gmail.com
            git add .
            git commit -m 'download data'
            git push
            echo downloaded.

      - name: DownLoad Data 02
        run: |
          wget -i filghturl01.txt -P flight/
          git config --local user.name lzxue
          git config --local user.email lzx199065@gmail.com
          git add .
          git commit -m 'download data'
          git push
          echo downloaded.

      - name: DownLoad Data 03
          run: |
            wget -i filghturl02.txt -P flight/
            git config --local user.name lzxue
            git config --local user.email lzx199065@gmail.com
            git add .
            git commit -m 'download data'
            git push
            echo downloaded.
            
      - name: DownLoad Data 04
        run: |
          wget -i filghturl03.txt -P flight/
          git config --local user.name lzxue
          git config --local user.email lzx199065@gmail.com
          git add .
          git commit -m 'download data'
          git push
          echo downloaded.

